### ISSUE TITLE
WeakMap shim missing

### ISSUE THREAD

**Issue by aecz** [angular/universal#648]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this Issue?**
- [x] universal

* **What is the current behavior?**
es6-shim does not implement WeakMap so universal fails in IE10 for example.
Broken since #557 

* **What is the expected behavior?**
Include a shim/polyfill for WeakMap.

- Angular version: 2.1.0
- Browser: [IE 10 | IE 9 | IE Mobile | Opera Mobile ]
- Language: [ TypeScript 2.0.2 ]
- Platform: [ NodeJs ]

**Comment by ethmelly** [comment]
Was searching for a solution for this also. Experiencing same issues.

**Comment by gdi2290** [comment]
good point. core-js should be used

**Comment by ethmelly** [comment]
I tried replacing es6-shim with core-js and now instead of WeakMap error i get:
Error: No provider for PlatformRef! which is also mentioned here [https://github.com/angular/universal-starter/issues/236](url)

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Comment by ocombe** [comment]
@ethmelly you just need to import weakmap / map / set right before you load the universal polyfill:

```ts
import "core-js/es6/weak-map";
import "core-js/es6/map";
import "core-js/es6/set";
import 'angular2-universal-polyfills';
```

This should fix the issue without disturbing anything else
